spring.datasource:
  driver-class-name: "org.h2.Driver"
  username: sa
  password:
  url: "jdbc:h2:file:./build/database"

spring.jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    hibernate.globally_quoted_identifiers: true
